"""Computational check of the automorphism statements:
 (1) tau_T and theta_{T,p} are automorphisms of the truncated tree (edge preserving);
 (2) the parity homomorphisms E_{lam,p} take the SAME value on every tau_T for the
     two mirror pairs p of lam = (3,2,1), but DIFFERENT values on a single theta;
 (3) with sympy: theta_{T,p} (T of shape (3,2,1)) is NOT in the group generated by
     all tau's restricted to depth <= N (N = 7), while every tau is a product of thetas;
     group orders are reported.
"""
import os, sys, time
sys.path.insert(0, os.path.dirname(__file__))
from tree import *
from young import is_symmetric

def run(N):
    t0 = time.time()
    levels, index = build_tree(N)
    nv = len(index)
    print(f"N={N}: {nv} vertices")
    syms = symmetric_vertices(levels, N - 1)
    taus = {}
    for T in syms:
        perm = permutation_of(lambda V, T=T: tau(T, V), levels, index)
        assert check_edge_preserving(perm, levels, index)
        taus[T] = perm
    thetas = {}
    for T in syms:
        lam = shape_of_vertex(T)
        for p in mirror_pairs(lam):
            perm = permutation_of(lambda V, T=T, p=p: theta(T, p, V), levels, index)
            assert check_edge_preserving(perm, levels, index)
            thetas[(T, p)] = perm
    print(f"  {len(taus)} tau generators, {len(thetas)} theta generators; all edge-preserving: OK")
    # (2) parity invariants for lam=(3,2,1)
    lam = (3, 2, 1)
    if N >= 7:
        pairs = mirror_pairs(lam)
        print("  mirror pairs of (3,2,1):", [sorted(p) for p in pairs])
        for T, perm in taus.items():
            vals = [parity_E(perm, levels, index, lam, p) for p in pairs]
            assert vals[0] == vals[1], (T, vals)
        print("  E_{(3,2,1),p1}(tau_T) == E_{(3,2,1),p2}(tau_T) for all", len(taus), "tau_T: OK")
        T321 = [T for T in levels[6] if shape_of_vertex(T) == lam][0]
        th = thetas[(T321, pairs[0])]
        vals = [parity_E(th, levels, index, lam, p) for p in pairs]
        print("  E values on theta_{T,p1} for T of shape (3,2,1):", vals, "(differ => theta not in closure<tau>)")
    # (3) sympy group membership
    from sympy.combinatorics import Permutation, PermutationGroup
    Gtau = PermutationGroup([Permutation(p) for p in taus.values()])
    Gtheta = PermutationGroup([Permutation(p) for p in thetas.values()])
    ot, oth = Gtau.order(), Gtheta.order()
    print(f"  |<tau>_N| = 2^{ot.bit_length()-1} (={ot}), |<theta>_N| = 2^{oth.bit_length()-1} (={oth})")
    assert ot & (ot - 1) == 0 and oth & (oth - 1) == 0
    for T, perm in taus.items():
        assert Gtheta.contains(Permutation(perm))
    print("  every tau_T lies in <theta>_N: OK")
    if N >= 7:
        print("  theta_{T,p1} (T of shape (3,2,1)) in <tau>_N ?", Gtau.contains(Permutation(th)))
    print(f"  [{time.time()-t0:.1f}s]")

if __name__ == "__main__":
    for N in [int(a) for a in sys.argv[1:]] or [5, 6, 7]:
        run(N)
