"""topend: the level polynomials G_i.
   g_i(lam) := (n)_i u_i(lam) / f^lam  = sum_{rho |- i} sigma(rho) |K_{rho}| chi^lam(rho)/f^lam
             = sum_{rhobar even-type, no 1's, |rhobar| <= i} sigma(rhobar) I(i-|rhobar|) C(n-|rhobar|, i-|rhobar|) omega_lam(K_rhobar)
   and omega_lam(K_rhobar) = Omega_rhobar(n; C_1, C_2, ...) from topend_fit (pickled).
 (1) build G_i(n; C) symbolically for i <= 10 (sympy, exact rationals);
 (2) verify G_i(lam) == (n)_i d_{n-i}(lam) / f^lam for all lam |- n <= NV;
 (3) leading forms (shifted weight: wt n = 1, wt C_k = k+1) and reduction modulo the algebra generated by
     n and the previous G's, to identify the NEW invariant at each level.
"""
import os, sys, pickle, itertools
from fractions import Fraction
from math import comb, factorial
import sympy as sp
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from topend_lib import *
from young import partitions, f_hook, involutions
from census import d_vector

HERE = os.path.dirname(os.path.abspath(__file__))
n = sp.Symbol('n')
Cs = {k: sp.Symbol(f'C{k}') for k in range(1, 11)}

def load_omegas():
    with open(os.path.join(HERE, 'topend_fit_results.pkl'), 'rb') as fh:
        terms = pickle.load(fh)
    Om = {}
    for rho, ts in terms.items():
        expr = 0
        for a, (j, mu) in ts:
            m = sp.Rational(a.numerator, a.denominator) * n ** j
            for p in mu: m *= Cs[p]
            expr += m
        Om[rho] = sp.expand(expr)
    return Om

def falling(x, k):
    r = 1
    for t in range(k): r *= (x - t)
    return r

def binom_poly(x, k):  # C(x, k) as polynomial
    return falling(x, k) / factorial(k)

def build_G(imax, Om):
    G = {}
    for i in range(imax + 1):
        expr = 0
        for rho, om in Om.items():
            s = sum(rho)
            if s > i: continue
            expr += sigma(rho) * involutions(i - s) * binom_poly(n - s, i - s) * om
        G[i] = sp.expand(expr)
    return G

def eval_poly(expr, lam):
    subs = {n: sum(lam)}
    for k, sym in Cs.items(): subs[sym] = C(lam, k)
    v = expr.subs(subs)
    return Fraction(int(sp.numer(v)), int(sp.denom(v)))

def verify_G(G, NV):
    bad = 0; cnt = 0
    for N in range(NV + 1):
        for lam in partitions(N):
            dv = d_vector(lam); f = f_hook(lam)
            for i in G:
                if i > N: continue
                lhs = eval_poly(G[i], lam)
                rhs = Fraction(falling(N, i) * dv[N - i], f)
                cnt += 1
                if lhs != rhs: bad += 1; print("G mismatch", lam, i)
    print(f"G_i(lam) == (n)_i u_i / f^lam for all lam |- n <= {NV}, i <= {max(G)}: {cnt} checks, {'OK' if bad==0 else str(bad)+' FAIL'}")
    return bad == 0

# ---- shifted weight grading
def weight(mono):
    d = mono.as_powers_dict()
    w = d.get(n, 0)
    for k, sym in Cs.items(): w += (k + 1) * d.get(sym, 0)
    return w

def homog_parts(expr):
    parts = {}
    for term in sp.Add.make_args(sp.expand(expr)):
        c, m = term.as_coeff_Mul()
        w = weight(m)
        parts[w] = parts.get(w, 0) + term
    return parts

def leading_form(expr):
    parts = homog_parts(expr)
    if not parts: return 0, -1
    w = max(parts); return sp.expand(parts[w]), w

def in_span_products(target, gens, w):
    """Is the weight-w form `target` a polynomial in the weighted-homogeneous gens (list of (form, weight))?
    Solve a linear system over all exponent vectors of total weight w. Returns coefficients or None."""
    # enumerate exponent vectors
    vecs = []
    def rec(idx, rem, cur):
        if idx == len(gens):
            if rem == 0: vecs.append(tuple(cur))
            return
        wt = gens[idx][1]
        for e in range(rem // wt + 1):
            rec(idx + 1, rem - e * wt, cur + [e])
    rec(0, w, [])
    if not vecs: return None
    prods = []
    for v in vecs:
        p = 1
        for e, (g, _) in zip(v, gens): p *= g ** e
        prods.append(sp.expand(p))
    syms = sp.symbols(f'a0:{len(vecs)}')
    eq = sp.expand(sum(a * p for a, p in zip(syms, prods)) - target)
    allvars = [n] + list(Cs.values())
    eqs = sp.Poly(eq, *allvars).coeffs()
    sol = sp.linsolve(eqs, syms)
    if not sol: return None
    sol = list(sol)[0]
    # set free parameters to 0
    free = set().union(*[s.free_symbols for s in sol]) & set(syms)
    sol = [s.subs({fv: 0 for fv in free}) for s in sol]
    return list(zip(vecs, sol))

def reduce_mod_algebra(F, gens_full):
    """gens_full: list of (g, lf(g), wt). Repeatedly kill the leading form of F using products of gens whose
    leading forms are algebraically independent. Returns (residual R, list of steps). If R == 0, F is in the algebra."""
    gens_lf = [(lf, w) for (_, lf, w) in gens_full]
    steps = []
    R = sp.expand(F)
    while R != 0:
        lf, w = leading_form(R)
        combo = in_span_products(lf, gens_lf, w)
        if combo is None:
            return R, steps
        sub = 0
        for v, a in combo:
            if a == 0: continue
            p = a
            for e, (g, _, _) in zip(v, gens_full): p *= g ** e
            sub += p
        R = sp.expand(R - sub)
        steps.append((w, combo))
    return R, steps

if __name__ == "__main__":
    NV = int(sys.argv[1]) if len(sys.argv) > 1 else 16
    Om = load_omegas()
    G = build_G(10, Om)
    for i in range(3, 11):
        print(f"G_{i} =", G[i])
    verify_G({i: G[i] for i in range(0, 11)}, NV)
    with open(os.path.join(HERE, 'topend_G.pkl'), 'wb') as fh:
        pickle.dump({i: sp.srepr(G[i]) for i in G}, fh)
    # reduction: algebra generated by n and G_3.. G_{i-1}
    gens = [(n, n, 1)]
    print("\n=== new invariant at each level (shifted weights: wt n=1, wt C_k=k+1) ===")
    for i in range(3, 11):
        R, steps = reduce_mod_algebra(G[i], gens)
        if R == 0:
            print(f"level {i}: G_{i} lies in Q[n, G_3..G_{i-1}]  (NO new information)")
        else:
            lf, w = leading_form(R)
            print(f"level {i}: NEW. leading form of the residual (weight {w}): {sp.factor(lf)}")
            print(f"          full residual G_{i} - (element of Q[n,G_3..G_{i-1}]) = {R}")
            gens.append((R, lf, w))
    print("\nGenerators (leading forms) of the algebra determined by (n, G_3..G_10):")
    for g, lf, w in gens: print("  weight", w, ":", sp.factor(lf))
